services:
  # Simulateur de données d'entrée
  acq-indus-py-input-simulator:
    build: ./py-input-tunnel-fan-simulator
    container_name: acq-indus-py-input-simulator
    depends_on:
      - acq-indus-mosquitto
    environment:
      - MQTT_BROKER=acq-indus-mosquitto
      - FAN_ID=TUNNEL_NORD_01
    restart: always
    networks:
      - acq-network
 
  # Le Broker MQTT (Le facteur qui distribue les messages)
  acq-indus-mosquitto:
    image: eclipse-mosquitto:2.0.18
    container_name: acq-indus-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    networks:
      - acq-network

  # La base de données (Optimisée pour le temps)
  acq-indus-influxdb:
    image: influxdb:2.7
    container_name: acq-indus-influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password123
      - DOCKER_INFLUXDB_INIT_ORG=bg_soft
      - DOCKER_INFLUXDB_INIT_BUCKET=fan_telemetry
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}
    volumes:
      - influx_data:/var/lib/influxdb2
    networks:
      - acq-network
      
  # Le pont entre MQTT et InfluxDB
  acq-indus-telegraf:
    image: telegraf:1.28
    container_name: acq-indus-telegraf
    depends_on:
      - acq-indus-mosquitto
      - acq-indus-influxdb
    environment:
      - INFLUX_URL=http://acq-indus-influxdb:8086
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - INFLUX_ORG=bg_soft
      - INFLUX_BUCKET=fan_telemetry
      - MQTT_BROKER=acq-indus-mosquitto
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    ports:
      - "8087:8087"
    restart: always
    networks:
      - acq-network

  # API IA qui analyse les données à la recherche d'anomalies (isolation forest)
  acq-indus-py-ia-brain-api:
    build: ./py-ia-brain-api
    container_name: acq-indus-py-ia-brain-api
    environment:
      - INFLUXDB_TOKEN=${INFLUX_TOKEN}
      - INFLUXDB_ORG=bg_soft
      - INFLUXDB_BUCKET=fan_telemetry
      - INFLUXDB_URL=http://acq-indus-influxdb:8086
      - AI_API_FILTER_ADDR="0.0.0.0"
      - AI_API_PORT=8000
    depends_on:
      - acq-indus-influxdb
    ports:
      - "8000:8000"
    restart: always
    networks:
      - acq-network

  # Frontend supervision application
  acq-indus-frontend-supervision:
    build: ./frontend/acq-indus-frontend
    container_name: acq-indus-frontend-supervision
    ports:
      - "8081:80" # Accessible sur http://localhost:8081
    depends_on:
      - acq-indus-py-ia-brain-api # Attend que l'API soit prête
    restart: always
    networks:
      - acq-network
    
  # Visualisation avancée des données
  acq-indus-grafana:
    image: grafana/grafana:10.4.2
    container_name: acq-indus-grafana
    ports:
      - "3001:3000" # On utilise 3001 pour éviter tout conflit
    env_file:
      - .env
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Mot de passe par défaut
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - INFLUX_ORG=${INFLUX_ORG}
      - INFLUX_BUCKET=${INFLUX_BUCKET}
      - INFLUX_TOKEN=${INFLUX_TOKEN}
    depends_on:
      - acq-indus-influxdb
      - acq-indus-loki
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    restart: always
    networks:
      - acq-network

  # Le moteur de stockage des logs
  acq-indus-loki:
    image: grafana/loki:2.9.4
    container_name: acq-indus-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    restart: always
    volumes:
      - loki_data:/loki
    networks:
      - acq-network

  # L'agent qui collecte les logs des conteneurs Docker
  acq-indus-promtail:
    image: grafana/promtail:2.9.4
    container_name: acq-indus-promtail
    volumes:
      - ./promtail/promtail-config.yaml:/etc/promtail/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - acq-indus-loki
    restart: always
    networks:
      - acq-network

  # Web portal
  acq-indus-portal:
    build: ./frontend/acq-indus-portal
    container_name: acq-indus-portal
    ports:
      - "8080:80" # Accessible sur http://localhost:8080
    restart: always
    networks:
      - acq-network


volumes:
  influx_data:
  grafana_data:
  loki_data:
  mosquitto_data:
  mosquitto_log:

networks:
  acq-network:
    driver: bridge