[agent]
  debug = true
  quiet = false

[[inputs.mqtt_consumer]]
  servers = ["tcp://$MQTT_BROKER:1883"]
  topics = ["tunnel/fan/+/telemetry"]
  data_format = "json"
  # On extrait fan_id et status comme tags pour faciliter les recherches
  tag_keys = ["fan_id", "status"]

[[outputs.influxdb_v2]]
  urls = ["$INFLUX_URL"]
  token = "$INFLUX_TOKEN"
  organization = "$INFLUX_ORG"
  bucket = "$INFLUX_BUCKET"

# Activer l'écoute des Webhooks HTTP sur le port 8087
[[inputs.http_listener_v2]]
  service_address = ":8087"
  paths = ["/grafana-webhook"]
  methods = ["POST"]
  data_format = "json_v2"
  
[[inputs.http_listener_v2.json_v2]]
  # Nom de la mesure dans InfluxDB
  measurement_name = "device_alarms"

  # SOLUTION : On cible directement le tableau d'alertes à la racine de la config json_v2
  [[inputs.http_listener_v2.json_v2.object]]
    path = "alerts"
    tags = ["status", "labels_alertname", "labels_fan_id"]
    included_keys = [
      "annotations_summary", 
      "annotations_description"
    ]
    # On force Telegraf à chercher le timestamp relatif au 'path' spécifié au-dessus
    timestamp_key = "startsAt"
    timestamp_format = "2006-01-02T15:04:05Z07:00"