thingsboard:
  host: acq-indus-thingsboard
  port: 1883
  security:
    accessToken: "${THINGSBOARD_GATEWAY_TOKEN}"
  statistics:
    enable: true
    interval: 60

storage:
  type: memory
  read_records_count: 100
  max_records_count: 10000
